### ISSUE TITLE
Please add python3 support

### ISSUE THREAD

**Issue by aelmahmoudy** [jdhirst1/ncc_cli#1]
Please support Python 3

Thanks

**Comment by nachter** [comment]
Indeed, to have Python 3 support would be great!

**Comment by nachter** [comment]
Hi again!
I created a fork and update the ncc_cli, so that it should work with python 3, allthough I didn't test all functionalities till now: https://github.com/nachter/ncc_cli. 
Best regards.

**Comment by jdhirst** [comment]
@nachter Looks good! Could you submit a pull request? I'd be happy to add python3 functionality to the tool; thanks for your work!

**Comment by jdhirst** [comment]
Merged, everything still works for python2.7 compatibility, so we can fix remaining py3 bugs post-merge.

**Comment by arthurzenika** [comment]
I just got : 

```
Traceback (most recent call last):
  File "/home/arthur/.virtualenvs/ncc-cli/bin/ncc", line 5, in <module>
    from ncc_cli.ncc_cli import main
  File "/home/arthur/.virtualenvs/ncc-cli/lib/python3.8/site-packages/ncc_cli/__init__.py", line 2, in <module>
    from .ncc_cli import *
  File "/home/arthur/.virtualenvs/ncc-cli/lib/python3.8/site-packages/ncc_cli/ncc_cli.py", line 48
    print bcolors.YELLOW + "--- Initial Client Setup ---\n\nNOTE: Please enter full URI for server name.\nExample: https://myserver.com/nextcloud\nFor security reasons, please do not use your plaintext password for this utility. You should generate an App password from your NextCloud settings page.\n" + bcolors.DEFAULT
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(bcolors.YELLOW + "--- Initial Client Setup ---\n\nNOTE: Please enter full URI for server name.\nExample: https://myserver.com/nextcloud\nFor security reasons, please do not use your plaintext password for this utility. You should generate an App password from your NextCloud settings page.\n" + bcolors.DEFAULT)?

```

is this related to this issue ?

**Comment by jdhirst** [comment]
@arthurlogilab You are using the old Python2.7 version of the utility. I have updated pypi to now contain the latest Python3 release. You should run `pip install -I ncc-cli==0.0.5` to update to the latest version. If there are still problems, let me know!

**Comment by arthurzenika** [comment]
@jdhirst1 great news ! Thanks ! `pip install --upgrade ncc-cli` solved the problem, thanks for uploading the new version.

**Comment by jdhirst** [comment]
Excellent!

**Comment by jdhirst** [comment]
Closing this for now, if any other python3-related issues come along, feel free to re-open.
