### ISSUE TITLE
Run server setup if run without argument and no config file exists

### ISSUE THREAD

**Issue by JohnMertz** [jdhirst1/ncc_cli#10]
Expected behaviour:

After installing the app with pip3, I would expect it to run the configuration wizard when the command is first run.

Current behaviour:

Since no argument is provided, it prints the help menu and exits. I simply ran `ncc ls` to trigger the configuration wizard instead, but this shouldn't be necessary.

Other note:

Probably something that would need to change when argparser is added (#9), so I don't know if it's worth the time right now. I'm still testing the waters to see how I like it but may fix this when I have time.

**Comment by jdhirst** [comment]
@JohnMertz I completely agree, I think that should go into branch 0.0.7 with argparse. I've been quite busy lately but might have some time to work on it this weekend. 

Thanks for submitting the issue!
