### ISSUE TITLE
How to delete/edit server?

### ISSUE THREAD

**Issue by chigkim** [jdhirst1/ncc_cli#13]
How can I re-initialize the setup or edit the url for server?
I'm on Ubuntu.

**Comment by jdhirst** [comment]
@chigkim the config is stored like this:
```
    home = os.path.expanduser("~")
    if os.name == 'nt': #If on Windows, use ini extension
        configfile = home + "/ncc_cfg.ini"
    else: #Elsewhere, use UNIX hidden filename
        configfile = home + "/.ncc_cfg"
```
So on linux its ~/.ncc_cfg and windows its %userprofile%\ncc_cfg.ini

Simply delete file and re-run the command to recreate the config file.
